// Code generated by codegen/errors.go — DO NOT EDIT.

package bridge

type CaptureError int

const (
	CaptureErrorOK CaptureError = 0
	CaptureErrorFailedCreateDXGIFactory CaptureError = 1
	CaptureErrorFailedConfigLoad CaptureError = 2
	CaptureErrorFailedEnumAdapters CaptureError = 3
	CaptureErrorFailedD3D11CreateDevice CaptureError = 4
	CaptureErrorFailedEnumOutputs CaptureError = 5
	CaptureErrorFailedAdapterConvert CaptureError = 6
	CaptureErrorFailedOutputConvert CaptureError = 7
	CaptureErrorFailedDuplicateOutput CaptureError = 8
	CaptureErrorFailedResourceConvert CaptureError = 9
	CaptureErrorFailedCreateTexture2D CaptureError = 10
	CaptureErrorFailedCreateOutputView CaptureError = 11
	CaptureErrorFailedCreateInputView CaptureError = 12
	CaptureErrorFailedCreateVideoProcessorEnumerator CaptureError = 13
	CaptureErrorFailedCreateVideoProcessor CaptureError = 14
	CaptureErrorFailedVideoProcessorBlt CaptureError = 15
	CaptureErrorFailedD3D11Map CaptureError = 16
	CaptureErrorFailedHandleCPURawFrame CaptureError = 17
	CaptureErrorFailedCapturedSlotLock CaptureError = 18
	CaptureErrorFailedX264EncoderOpen CaptureError = 19
	CaptureErrorFailedX264Encode CaptureError = 20
	CaptureErrorFailedEncoderBufferEmplace CaptureError = 21
	CaptureErrorInvalidDuplication CaptureError = 22
	CaptureErrorInvalidX264Preset CaptureError = 23
	CaptureErrorInvalidX264Profile CaptureError = 24
	CaptureErrorInvalidCapturedTexture CaptureError = 25
	CaptureErrorInvalidTextureMap CaptureError = 26
	CaptureErrorEmptyCapturedBuffer CaptureError = 27
	CaptureErrorFailedCacheLastCapturedFrame CaptureError = 28
	CaptureErrorFailedCreateD3D11VideoDeviceOrContext CaptureError = 29
	CaptureErrorInvalidD3D11VideoDeviceOrContext CaptureError = 30
	CaptureErrorDuplicationLost CaptureError = 31
	CaptureErrorNoCachedFrame CaptureError = 32
)

var captureErrorDescriptions = map[CaptureError]string{
	CaptureErrorOK: "Success",
	CaptureErrorFailedCreateDXGIFactory: "Failed to create DXGI factory",
	CaptureErrorFailedConfigLoad: "Failed to load YAML config",
	CaptureErrorFailedEnumAdapters: "Failed to enumerate DXGI adapters",
	CaptureErrorFailedD3D11CreateDevice: "Failed to create D3D11 device",
	CaptureErrorFailedEnumOutputs: "Failed to enumerate outputs",
	CaptureErrorFailedAdapterConvert: "Failed to convert adapter",
	CaptureErrorFailedOutputConvert: "Failed to convert output",
	CaptureErrorFailedDuplicateOutput: "Failed to duplicate output",
	CaptureErrorFailedResourceConvert: "Failed to convert resource",
	CaptureErrorFailedCreateTexture2D: "Failed to create texture",
	CaptureErrorFailedCreateOutputView: "Failed to create output view",
	CaptureErrorFailedCreateInputView: "Failed to create input view",
	CaptureErrorFailedCreateVideoProcessorEnumerator: "Failed to create video processor enumerator",
	CaptureErrorFailedCreateVideoProcessor: "Failed to create video processor",
	CaptureErrorFailedVideoProcessorBlt: "Failed to execute video processor BLT",
	CaptureErrorFailedD3D11Map: "Failed to map D3D11 texture",
	CaptureErrorFailedHandleCPURawFrame: "Failed to handle CPU raw frame",
	CaptureErrorFailedCapturedSlotLock: "Failed to lock captured slot",
	CaptureErrorFailedX264EncoderOpen: "Failed to open x264 encoder",
	CaptureErrorFailedX264Encode: "Failed to encode frame with x264",
	CaptureErrorFailedEncoderBufferEmplace: "Failed to emplace frame to encoder buffer",
	CaptureErrorInvalidDuplication: "Invalid duplication",
	CaptureErrorInvalidX264Preset: "Invalid x264 preset",
	CaptureErrorInvalidX264Profile: "Invalid x264 profile",
	CaptureErrorInvalidCapturedTexture: "Invalid captured texture",
	CaptureErrorInvalidTextureMap: "Invalid texture map",
	CaptureErrorEmptyCapturedBuffer: "Empty captured buffer",
	CaptureErrorFailedCacheLastCapturedFrame: "Failed to cache last captured frame before capturer restart",
	CaptureErrorFailedCreateD3D11VideoDeviceOrContext: "Failed to create ID3D11VideoDevice/Context1 (CHECK THE GPU DRIVER)",
	CaptureErrorInvalidD3D11VideoDeviceOrContext: "Invalid ID3D11VideoDevice/Context1 (CHECK THE GPU DRIVER)",
	CaptureErrorDuplicationLost: "Desktop duplication lost",
	CaptureErrorNoCachedFrame: "Empty cached frame",
}

func (e CaptureError) Error() string {
	if desc, ok := captureErrorDescriptions[e]; ok {
		return desc
	}
	return "unknown error"
}
