// Code generated by codegen/errors.go — DO NOT EDIT.

#include <unordered_map>

#include "errors.h"

namespace {
const auto error_descriptions = std::unordered_map<int, const char*>{
	{ 0, "Success" },
	{ 1, "Failed to create DXGI factory" },
	{ 2, "Failed to load YAML config" },
	{ 3, "Failed to enumerate DXGI adapters" },
	{ 4, "Failed to create D3D11 device" },
	{ 5, "Failed to enumerate outputs" },
	{ 6, "Failed to convert adapter" },
	{ 7, "Failed to convert output" },
	{ 8, "Failed to duplicate output" },
	{ 9, "Failed to convert resource" },
	{ 10, "Failed to create texture" },
	{ 11, "Failed to create output view" },
	{ 12, "Failed to create input view" },
	{ 13, "Failed to create video processor enumerator" },
	{ 14, "Failed to create video processor" },
	{ 15, "Failed to execute video processor BLT" },
	{ 16, "Failed to map D3D11 texture" },
	{ 17, "Failed to handle CPU raw frame" },
	{ 18, "Failed to lock captured slot" },
	{ 19, "Failed to open x264 encoder" },
	{ 20, "Failed to encode frame with x264" },
	{ 21, "Failed to emplace frame to encoder buffer" },
	{ 22, "Invalid duplication" },
	{ 23, "Invalid x264 preset" },
	{ 24, "Invalid x264 profile" },
	{ 25, "Invalid captured texture" },
	{ 26, "Invalid texture map" },
	{ 27, "Empty captured buffer" },
	{ 28, "Failed to cache last captured frame before capturer restart" },
	{ 29, "Failed to create ID3D11VideoDevice/Context1 (CHECK THE GPU DRIVER)" },
	{ 30, "Invalid ID3D11VideoDevice/Context1 (CHECK THE GPU DRIVER)" },
	{ 31, "Desktop duplication lost" },
	{ 32, "Empty cached frame" },
};
}

const char* capture_native_get_error_description(int error) {
	auto it = error_descriptions.find(error);
	return it != error_descriptions.end() ? it->second : "Unknown error";
}
