// Code generated by codegen/errors.go — DO NOT EDIT.

#pragma once

#ifdef CAPTURE_NATIVE_BUILD
    #define CAPTURE_API __declspec(dllexport)
#else
    #define CAPTURE_API __declspec(dllimport)
#endif

#ifdef __cplusplus
extern "C" {
#endif

enum CaptureError {
	CaptureErrorOK = 0,
	CaptureErrorFailedCreateDXGIFactory = 1,
	CaptureErrorFailedConfigLoad = 2,
	CaptureErrorFailedEnumAdapters = 3,
	CaptureErrorFailedD3D11CreateDevice = 4,
	CaptureErrorFailedEnumOutputs = 5,
	CaptureErrorFailedAdapterConvert = 6,
	CaptureErrorFailedOutputConvert = 7,
	CaptureErrorFailedDuplicateOutput = 8,
	CaptureErrorFailedResourceConvert = 9,
	CaptureErrorFailedCreateTexture2D = 10,
	CaptureErrorFailedCreateOutputView = 11,
	CaptureErrorFailedCreateInputView = 12,
	CaptureErrorFailedCreateVideoProcessorEnumerator = 13,
	CaptureErrorFailedCreateVideoProcessor = 14,
	CaptureErrorFailedVideoProcessorBlt = 15,
	CaptureErrorFailedD3D11Map = 16,
	CaptureErrorFailedHandleCPURawFrame = 17,
	CaptureErrorFailedCapturedSlotLock = 18,
	CaptureErrorFailedX264EncoderOpen = 19,
	CaptureErrorFailedX264Encode = 20,
	CaptureErrorFailedEncoderBufferEmplace = 21,
	CaptureErrorInvalidDuplication = 22,
	CaptureErrorInvalidX264Preset = 23,
	CaptureErrorInvalidX264Profile = 24,
	CaptureErrorInvalidCapturedTexture = 25,
	CaptureErrorInvalidTextureMap = 26,
	CaptureErrorEmptyCapturedBuffer = 27,
	CaptureErrorFailedCacheLastCapturedFrame = 28,
	CaptureErrorFailedCreateD3D11VideoDeviceOrContext = 29,
	CaptureErrorInvalidD3D11VideoDeviceOrContext = 30,
	CaptureErrorDuplicationLost = 31,
	CaptureErrorNoCachedFrame = 32,
};

/// @brief Get human-readable description for a CaptureError
/// @param error Error code
/// @return Description string (never NULL, "Unknown error" for incorrect error)
CAPTURE_API const char* capture_native_get_error_description(int error);

#ifdef __cplusplus
}
#endif
