// Code generated by codegen/errors.go — DO NOT EDIT.

#pragma once

#ifdef CAPTURE_NATIVE_BUILD
    #define CAPTURE_API __declspec(dllexport)
#else
    #define CAPTURE_API __declspec(dllimport)
#endif

#ifdef __cplusplus
extern "C" {
#endif

enum CaptureError {
	CaptureErrorOK = 0,
	CaptureErrorFailedCreateDXGIFactory = 1,
	CaptureErrorFailedConfigLoad = 2,
	CaptureErrorFailedEnumAdapters = 3,
	CaptureErrorFailedD3D11CreateDevice = 4,
	CaptureErrorFailedEnumOutputs = 5,
	CaptureErrorFailedOutputConvert = 6,
	CaptureErrorFailedDuplicateOutput = 7,
	CaptureErrorFailedAcquireNextFrame = 8,
	CaptureErrorFailedResourceConvert = 9,
	CaptureErrorFailedCreateTexture2D = 10,
	CaptureErrorFailedCreateOutputView = 11,
	CaptureErrorFailedCreateInputView = 12,
	CaptureErrorFailedVideoProcessorBlt = 13,
	CaptureErrorFailedD3D11Map = 14,
	CaptureErrorFailedEncoderInitialization = 15,
	CaptureErrorFailedHandleCPURawFrame = 16,
	CaptureErrorFailedCapturedSlotLock = 17,
	CaptureErrorFailedX264EncoderOpen = 18,
	CaptureErrorFailedX264Encode = 19,
	CaptureErrorFailedEncoderBufferEmplace = 20,
	CaptureErrorInvalidDXGIFactory = 21,
	CaptureErrorInvalidDuplicate = 22,
	CaptureErrorInvalidX264Preset = 23,
	CaptureErrorInvalidX264Profile = 24,
	CaptureErrorInvalidCapturedTexture = 25,
	CaptureErrorInvalidTextureMap = 26,
	CaptureErrorEmptyCapturedBuffer = 27,
	CaptureErrorAccessLost = 28,
};

/// @brief Get human-readable description for a CaptureError
/// @param error Error code
/// @return Description string (never NULL, "Unknown error" for incorrect error)
CAPTURE_API const char* capture_native_get_error_description(int error);

#ifdef __cplusplus
}
#endif
