#pragma once

#include <stdint.h>

// encoded H.264 frame
struct EncodedFrame {
    uint8_t const* data;
    uint32_t       size;
    uint64_t       pts;
    int            keyframe;
};

enum CaptureError {
    CAPTURE_ERROR_OK,
    CAPTURE_ERROR_FAILED_CREATE_DXGI_FACTORY = 1,
    CAPTURE_ERROR_FAILED_CONFIG_LOAD,
    CAPTURE_ERROR_FAILED_ENUM_ADAPTERS,
    CAPTURE_ERROR_FAILED_D3D11_CREATE_DEVICE,
    CAPTURE_ERROR_FAILED_ENUM_OUTPUTS,
    CAPTURE_ERROR_FAILED_OUTPUT_CONVERT,
    CAPTURE_ERROR_FAILED_DUPLICATE_OUTPUT,
    CAPTURE_ERROR_FAILED_ACQUIRE_NEXT_FRAME,
    CAPTURE_ERROR_FAILED_RESOURCE_CONVERT,
    CAPTURE_ERROR_FAILED_CREATE_TEXTURE2D,
    CAPTURE_ERROR_FAILED_CREATE_OUTPUT_VIEW,
    CAPTURE_ERROR_FAILED_CREATE_INPUT_VIEW,
    CAPTURE_ERROR_FAILED_VIDEO_PROCESSOR_BLT,
    CAPTURE_ERROR_FAILED_D3D11_MAP,
    CAPTURE_ERROR_FAILED_ENCODER_INITIALIZATION,
    CAPTURE_ERROR_FAILED_HANDLE_CPU_RAW_FRAME,
    CAPTURE_ERROR_FAILED_CAPTURED_SLOT_LOCK,
    CAPTURE_ERROR_FAILED_X264_ENCODER_OPEN,
    CAPTURE_ERROR_FAILED_X264_ENCODE,
    CAPTURE_ERROR_FAILED_ENCODER_BUFFER_EMPLACE,

    CAPTURE_ERROR_INVALID_DXGI_FACTORY = 1000,
    CAPTURE_ERROR_INVALID_DUPLICATE,
    CAPTURE_ERROR_INVALID_X264_PRESET,
    CAPTURE_ERROR_INVALID_X264_PROFILE,
    CAPTURE_ERROR_INVALID_CAPTURED_TEXTURE,
    CAPTURE_ERROR_INVALID_TEXTURE_MAP,
    CAPTURE_ERROR_EMPTY_CAPTURED_BUFFER,

    CAPTURE_ERROR_ACCESS_LOST = 2000,
};
