// Code generated by codegen/errors.go — DO NOT EDIT.

package internal

type CaptureError int

const (
	CaptureErrorOK CaptureError = 0
	CaptureErrorFailedCreateDXGIFactory CaptureError = 1
	CaptureErrorFailedConfigLoad CaptureError = 2
	CaptureErrorFailedEnumAdapters CaptureError = 3
	CaptureErrorFailedD3D11CreateDevice CaptureError = 4
	CaptureErrorFailedEnumOutputs CaptureError = 5
	CaptureErrorFailedOutputConvert CaptureError = 6
	CaptureErrorFailedDuplicateOutput CaptureError = 7
	CaptureErrorFailedAcquireNextFrame CaptureError = 8
	CaptureErrorFailedResourceConvert CaptureError = 9
	CaptureErrorFailedCreateTexture2D CaptureError = 10
	CaptureErrorFailedCreateOutputView CaptureError = 11
	CaptureErrorFailedCreateInputView CaptureError = 12
	CaptureErrorFailedVideoProcessorBlt CaptureError = 13
	CaptureErrorFailedD3D11Map CaptureError = 14
	CaptureErrorFailedEncoderInitialization CaptureError = 15
	CaptureErrorFailedHandleCPURawFrame CaptureError = 16
	CaptureErrorFailedCapturedSlotLock CaptureError = 17
	CaptureErrorFailedX264EncoderOpen CaptureError = 18
	CaptureErrorFailedX264Encode CaptureError = 19
	CaptureErrorFailedEncoderBufferEmplace CaptureError = 20
	CaptureErrorInvalidDXGIFactory CaptureError = 21
	CaptureErrorInvalidDuplicate CaptureError = 22
	CaptureErrorInvalidX264Preset CaptureError = 23
	CaptureErrorInvalidX264Profile CaptureError = 24
	CaptureErrorInvalidCapturedTexture CaptureError = 25
	CaptureErrorInvalidTextureMap CaptureError = 26
	CaptureErrorEmptyCapturedBuffer CaptureError = 27
	CaptureErrorAccessLost CaptureError = 28
)

var captureErrorDescriptions = map[CaptureError]string{
	CaptureErrorOK: "Success",
	CaptureErrorFailedCreateDXGIFactory: "Failed to create DXGI factory",
	CaptureErrorFailedConfigLoad: "Failed to load YAML config",
	CaptureErrorFailedEnumAdapters: "Failed to enumerate DXGI adapters",
	CaptureErrorFailedD3D11CreateDevice: "Failed to create D3D11 device",
	CaptureErrorFailedEnumOutputs: "Failed to enumerate outputs",
	CaptureErrorFailedOutputConvert: "Failed to convert output",
	CaptureErrorFailedDuplicateOutput: "Failed to duplicate output",
	CaptureErrorFailedAcquireNextFrame: "Failed to acquire next frame",
	CaptureErrorFailedResourceConvert: "Failed to convert resource",
	CaptureErrorFailedCreateTexture2D: "Failed to create texture",
	CaptureErrorFailedCreateOutputView: "Failed to create output view",
	CaptureErrorFailedCreateInputView: "Failed to create input view",
	CaptureErrorFailedVideoProcessorBlt: "Failed to execute video processor BLT",
	CaptureErrorFailedD3D11Map: "Failed to map D3D11 texture",
	CaptureErrorFailedEncoderInitialization: "Failed to initialize encoder",
	CaptureErrorFailedHandleCPURawFrame: "Failed to handle CPU raw frame",
	CaptureErrorFailedCapturedSlotLock: "Failed to lock captured slot",
	CaptureErrorFailedX264EncoderOpen: "Failed to open x264 encoder",
	CaptureErrorFailedX264Encode: "Failed to encode frame with x264",
	CaptureErrorFailedEncoderBufferEmplace: "Failed to emplace frame to encoder buffer",
	CaptureErrorInvalidDXGIFactory: "Invalid DXGI factory",
	CaptureErrorInvalidDuplicate: "Invalid duplication",
	CaptureErrorInvalidX264Preset: "Invalid x264 preset",
	CaptureErrorInvalidX264Profile: "Invalid x264 profile",
	CaptureErrorInvalidCapturedTexture: "Invalid captured texture",
	CaptureErrorInvalidTextureMap: "Invalid texture map",
	CaptureErrorEmptyCapturedBuffer: "Empty captured buffer",
	CaptureErrorAccessLost: "Access lost (desktop changed)",
}

func (e CaptureError) Error() string {
	if desc, ok := captureErrorDescriptions[e]; ok {
		return desc
	}
	return "unknown error"
}
